name: fn_ui_kit
description: 公用ui组件
version: 1.1.0
homepage:

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  icon_font_generator: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
     - family: fn_design_icons
       fonts:
         - asset: lib/assets/fn_icons_font.otf

#图标资源生成规则配置
icon_font:
  input_svg_dir: "icons"
  output_font_file: "lib/assets/fn_icons_font.otf"

  output_class_file: "lib/assets/fn_icons.dart"
  class_name: "FNIcons"
  package: fn_ui_kit
  format: true

  font_name: "fn_design_icons"
  normalize: false
  ignore_shapes: false


  recursive: true
  verbose: false